### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by emmrichd** [mruettgers/SMLReader#13]
Hello,

how do I reset all settings? Are the settings kept, if I flash again?

Regards, Dieter

**Comment by mruettgers** [comment]
Hey Dieter,

As long as the value of `CONFIG_VERSION` in `config.h` is not changed the settings should be kept.
The settings are stored by https://github.com/prampec/IotWebConf in the EEPROM.

In the long term I would like to rewrite this stuff to make the settings being stored in SPIFFS.

Regards,
Michael
