### ISSUE TITLE
Question: OTA update possible?

### ISSUE THREAD

**Issue by derandiunddasbo** [mruettgers/SMLReader#29]
Is it possible to use the OTA update provided by IOTWebConf to upload new/self compiled firmware versions?

**Comment by mruettgers** [comment]
OTA updates should already work: http://[your-ip]/firmware (or use the link on the start page).

**Comment by derandiunddasbo** [comment]
Ok, thanks for the clarification. I just wanted to make sure, I won't "brick" my device by attempting an OTA update. It's sitting at a quite inaccessible place and I want to avoid having it to update over a wired connection.

**Comment by derandiunddasbo** [comment]
Just wanted to give a quick follow up: Building the firmware and the OTA update worked fine. 

After reboot I was a bit confused at first, because I couldn't reach the web config page anymore and it didn't publish anything to the mqtt server. But then I realized, that the devices captive portal was active again and I just had to reconfigure its WiFi and mqtt settings.
