### ISSUE TITLE
Question: get power per phase

### ISSUE THREAD

**Issue by HakamSaffour** [mruettgers/SMLReader#32]
Hello,
I have smart meter (ISKARA MT631) and I want to get the power consumption of each phase. Is this possible?

The SMLReader sends the following infos:

![image](https://user-images.githubusercontent.com/11553465/129445468-48ab99e1-659a-45e5-a77a-d5d3fd1dece0.png)

**Comment by hamster65** [comment]
hi,
as far as I understand how SML reader works, it would automatically output that if received from the meter.

**Comment by syssi** [comment]
The number of data points depends on your meter (firmware, configuration and pin number entered or not).

**Comment by HakamSaffour** [comment]
I entered the pin number, but the infos are the same.
the meter does not seems to be configurable
I am thinking of using Shelly 3EM to get the power per phase.
Thanks
