### ISSUE TITLE
SML Reader on ESP01

### ISSUE THREAD

**Issue by Diddlik** [mruettgers/SMLReader#36]
I'm trying to create SML Reader for ESP01, with the adjustment of platfomio.ini it worked so far, now at the start was problematic with WIFI. Only reflash via esptool worked, with platformio did not work. 
After all problems now remains in the console at the status: 
initializing sensor 1:

**Comment by mruettgers** [comment]
@Diddlik Can you please post the whole debug output of SMLReader? What GPIO-Pin of the ESP01 are you using to connect the reading head?

**Comment by mruettgers** [comment]
Ok. I was just wondering because GPIO2 and GPIO0 (the only ones available on the ESP01) have a special meaning during startup and the read head could interfere with them.
