### ISSUE TITLE
Feature Request - send intervall on the config page

### ISSUE THREAD

**Issue by kr0815** [mruettgers/SMLReader#37]
Hi Michael,

thanks a lot again for your great work ::-)
My 2 Meters had been read out for 6 Months now without any issue

Now, more and more friends, as they also got new meters, want to see their power consumption
Most of these people have no home automation, are not familiar with programming

I give them a personal site on my webhostet volkszahler account, so they could see their power usage, they are totaly happy

Most of their meters send a message every second - several values
I don´t want the data getting that big

I know i could set the interval to like 60 seconds
But this always means a rebuild / reflash of the ESP

At the point of  installation it´s very handy to see the ESP LED blinking / get a new MQTT Message each second, makes it easy to get the sensor in the right position, but after the proof of work i have to change that

Do you see any chance to implement a config-page-changeable send interval in near future?

Best regards

Klaus

**Comment by lk3de** [comment]
I'm having the exact same use-case (providing ESPs to friends) and such a feature would be awesome! 💯

Alternative proposal: probably we can blink the LED once when an SML sequence is received, and multiple times (like it does now) when an MQTT message is fired. That would allow getting the right sensor position easily while still using a higher MQTT push interval.

**Comment by kr0815** [comment]
Hi Michael,

you seem very busy :-)  hope you had a quiet holiday season

Do you see any chance to include that feature in the future?

I could try it myself, but it will be a really hard nut for me :-)

Maybe it´s easyer to add a Switch / GPIO Contact to switch between 1 and 60 seconds?

Cheers
Klaus

**Comment by mruettgers** [comment]
Hey Klaus,

That's unfortunately true, I'm too busy at the moment to continue developing SMLReader or its successor.
My sons and the tasks around the house just take up too much of my time.
I hope I have some more time within the next couple of months.

In the current version, it is not so easy to extend the configuration so that the existing configuration is preserved after flashing newer builds.
The successor of SMLReader will be shipped with a React based web interface and will provide a better way to configure the devices.

Cheers,

Michael

**Comment by kr0815** [comment]
Hi Michael,
i totally understand, enjoy the time wth your sons :-)

About SML reader - i don´t think we need a successor
I have to confess - you send newer builds- i never installed them
Why? the curent installation works perfect, wonderfull job you did :-)

But the more i think about it - father in law is asking for a meter for 5 months now :-) - 
would it be easy to integrate something like 
if GPIO X is high send each 60 seconds
if GPIO Y is high send each 180 seconds

There are enough free GPIOs on the ESP8266, i could use jumpers in field to decide the intervall SMLReader is sending

maybe this is a fast workaround for the moment?
Hope you could assist a little bit  ? :-)

**Comment by kr0815** [comment]
found the solution myself - so stupid ....

Just configure 3 different inputs - same name, but for example 0, 60 and 120 sec interval

**Comment by mruettgers** [comment]
Sorry for not getting back to you.
But I'm glad, that you found a workaround for this issue :-).
