### ISSUE TITLE
Reading two SmartMeters with one ESP

### ISSUE THREAD

**Issue by T2FF** [mruettgers/SMLReader#40]
Hello,
first of all i like your project very much and thanks for sharing it !

Now my question:
I have two smartmeters and would like to read them simultaneously via two BPW40 transistors with one ESP.
Is this possible and if so what changes in the code do I have to make and how do I connect the second transitor to the ESP ?

**Comment by mruettgers** [comment]
Hey @T2FF,

multiple reading heads should work without problems.
You just have to configure the heads as described here:
https://github.com/mruettgers/SMLReader#configuration

**Comment by syssi** [comment]
I'm reading 3 smartmeters with one ESP without issues.

**Comment by T2FF** [comment]
okay thank you very much for the quick feedback.

Is this correct?
![SML](https://user-images.githubusercontent.com/84192658/141143753-0c1c564a-a52a-4860-b405-b93b11d02f43.jpg)


Because I do not quite understand the circuit. According to my understanding, if the 3.3V pin is an "ideal" voltage source, the same potential should always be present at the digital inputs. The only thing that changes in my opinion is the current flow, because the transistors are connected in parallel, but digital inputs can not measure current flow?

**Comment by benniju** [comment]
In the image the two inputs are basically put in parallel, so they will always turn on and off together. You need two separate resistors for each sensor.

**Comment by T2FF** [comment]
So you mean something like this ?
![SML](https://user-images.githubusercontent.com/84192658/141149857-7f293460-6f06-4e37-9c94-4c1e02c285f1.jpg)
