### ISSUE TITLE
no wifi connection

### ISSUE THREAD

**Issue by trombose009** [mruettgers/SMLReader#49]
is it correct that I just have to fill out the following lines in the config.h file for connecting to wifi sucessfully?

const char *WIFI_AP_SSID = "sfsdfsdfsdfsd";
const char *WIFI_AP_DEFAULT_PASSWORD = "545643563456435";

the device should work. It starts blinking typically if I place the sensor to the meter. But I can't find the device on my router and I get no mqtt messages to the broker :(
It'S a node mcu V3 ESP8266.

**Comment by mruettgers** [comment]
No, `WIFI_AP_SSID` and `WIFI_AP_DEFAULT_PASSWORD` are not meant to be used to configure the credentials of your local network. Instead they are used to configure the name and the password of the wifi access point provided by SMLReader to allow the configuration of your wifi credentials via a web interface (`http://192.168.4.1`).

**Comment by trombose009** [comment]
omg!  sorry. yes. I am an idiot :P
