### ISSUE TITLE
The meaning of MQTT topics

### ISSUE THREAD

**Issue by HakamSaffour** [mruettgers/SMLReader#5]
Hi,
Can you explain what is the meaning of the MQTT topics

smartmeter/mains/sensor/1/obis/1-0:1.8.0/255/value 3546245.9
smartmeter/mains/sensor/1/obis/1-0:2.8.0/255/value 13.2
smartmeter/mains/sensor/1/obis/1-0:1.8.1/255/value 0.0
smartmeter/mains/sensor/1/obis/1-0:2.8.1/255/value 13.2
smartmeter/mains/sensor/1/obis/1-0:1.8.2/255/value 3546245.9
smartmeter/mains/sensor/1/obis/1-0:2.8.2/255/value 0.0
smartmeter/mains/sensor/1/obis/1-0:16.7.0/255/value 451.2

on my meter, I am getting the following values
![image](https://user-images.githubusercontent.com/11553465/93924266-cab11e80-fd14-11ea-9bb9-c376eb206bfe.png)

Thanks in advance

**Comment by ostpol** [comment]
Hi @HakamSaffour,

smartmeter/mains/sensor/1/obis/**1-0:1.8.0**/255/value 3546245.9

The bold part ist the OBIS identifier. 1.8.0 should be the overall consumption of your meter.

Other identifiers are documented in this (german) [document](https://www.bundesnetzagentur.de/DE/Service-Funktionen/Beschlusskammern/BK06/BK6_81_GPKE_GeLi/Mitteilung_nr_62/Anlagen/Codeliste_OBIS_Kennzahlen_2.2g.pdf?__blob=publicationFile&v=2). 

I hope it helps a bit.


– T

**Comment by mruettgers** [comment]
Hi @HakamSaffour,

in addition to @ostpol's answer:

1-0:16.7.0 should be the current consumption (Wirkleistung Momentan).

Michael

**Comment by HakamSaffour** [comment]
Vielen Dank @ostpol  und @mruettgers
