### ISSUE TITLE
Add the possibility to disable the AP

### ISSUE THREAD

**Issue by HakamSaffour** [mruettgers/SMLReader#8]
for security reasons and in order not have too many AP's around you, please add the possibility to disable the AP in the web configuration page

**Comment by mruettgers** [comment]
Hi,

I don't think that this is necessary because the AP mode is enabled only in case the ESP is not being able to connect to your WiFi in STA mode.
So there is no additional WiFi AP around if everything is working as expected.

Michael

**Comment by HakamSaffour** [comment]
Yes, you are right.
I am closing this issue
