### ISSUE TITLE
Web-interface requires login

### ISSUE THREAD

**Issue by Syntoxr** [mruettgers/SMLReader#9]
I think it isn't an issue but, I couldn't figure out what the login credentials for the web-interface are.

Thanks for your work!

**Comment by mruettgers** [comment]
Hey @Syntoxr,

user `admin` and the initially set AP password should work.
At least they worked for me right now.

Michael

**Comment by mruettgers** [comment]
I just updated the docs accordingly

**Comment by Syntoxr** [comment]
Hi @mruettgers ,

Thanks for your quick reply.
I tried standard usernames and passwords before (user `admin` and password `AP password` too) but that didn't work.
I'll try again later that day.

**Comment by mruettgers** [comment]
With `AP password` I meant the password you've configured during the initinal setup.

**Comment by Syntoxr** [comment]
After flashing again it worked. I think I mistyped the password when setting it.
Thanks for your help.
